name: Example Server
port: "6996"
urls:
    local: http://localhost
    private: http://192.168.4.23
    public: http://192.168.4.23
    admin_login: c13486d7b830c395
    admin_prefix: 520ccc
    login: ebc47c45d3612c4e
    prefix:
cookie:
    user:
        name: example-server
        message: 2916e8cc8bc847a2
    admin:
        name: example-server-admin
        message: 02111aed80dd1c18
    secret: yqMEhVQKT4pk4lqP5ebnUImQzfQYeDMJEao6+iDTkhc=
creds:
    api_key: b0651f15e0ef8dd4
    admin_username: 469923c96826c9a7
    admin_password: 5787937209d4e82f
    encryption_key: 715b9ff14c766cbe5510e6b09fcf75d8
    kyber:
        private: ""
        public: ""
    openai_key: ""
time_zone: ""
allow_origins: []
save_files_path: /Users/morpheous/WORKSPACE/GO/GO_SERVER/SAVE_FILES
bolt:
    path: 30b301.db
    prefix: 1cfb29
redis:
    host: ""
    port: ""
    password: ""
    number: 1
    prefix: e0e2c5
    enabled: false
docker:
    name: private-example-server
git:
    url: https://github.com/0187773933/GO_SERVER.git
    ssh_url: git@github.com:0187773933/GO_SERVER.git
go:
    version: 1.22.2
    os: linux
    arch: amd64
log:
    server_name: ""
    server_base_url: ""
    server_live_url: ""
    server_private_url: ""
    server_public_url: ""
    server_port: ""
    server_api_key: ""
    server_login_url_prefix: ""
    server_url_prefix: ""
    server_cookie_name: ""
    server_cookie_secret: ""
    server_cookie_admin_secret_message: ""
    server_cookie_secret_message: ""
    server_allow_origins: ""
    admin_username: ""
    admin_password: ""
    time_zone: America/New_York
    save_files_path: ""
    bolt_db_path: e40e21.db
    encryption_key: 4d2ba059e64a98937948be42d560e26d
    log_level: debug
    log_key: be0a38